# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-04-09 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('age', models.SmallIntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('classid', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'stu',
            },
        ),
        migrations.RunSQL(["insert into stu values (1, 'shihj', 30, 'm', '15076')"])
    ]
